name = "BayesianSamplerModel"
uuid = "8ce4b022-2fa4-48bd-8d17-d16215eb6b0c"
authors = ["itsdfish and contributors"]
version = "1.0.0-DEV"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[compat]
ComponentArrays = "0.13"
Distributions = "0.25.0"
SafeTestsets = "0.0.1,0.1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
